// ---------------------------------------------------------------------------
// Canonical line-item lookup shared by the Linkage Diagram and the Living
// Model. Maps abstract IDs (`is-revenue`, `bs-ar`, `cf-capex`, ...) to one or
// more regexes that match the messy real-world labels in SEC filings.
//
// Two surfaces depend on this:
//   - LinkageDiagram (statement nodes + rollforward math)
//   - Living Model projection engine (driver baselines from historicals)
//
// Source of truth for label variants. Keep regexes anchored where possible.
// ---------------------------------------------------------------------------

export const PATTERNS = {
  income_statement: {
    'is-revenue':      [/^(net\s+)?(total\s+)?(net\s+)?revenue(s)?$/i, /^net\s+sales$/i, /^total\s+net\s+sales$/i, /^sales$/i, /^total\s+revenues?$/i],
    'is-cogs':         [/^(total\s+)?cost\s+of\s+(goods|revenue|sales|products)/i],
    'is-gross-profit': [/^gross\s+(profit|margin)/i],
    'is-opex':         [/^(total\s+)?operating\s+expenses?$/i],
    'is-depreciation': [/^depreciation/i],
    'is-operating':    [/^operating\s+(income|profit)/i, /^income\s+from\s+operations/i],
    'is-interest':     [/^interest\s+expense/i],
    'is-pretax':       [/^(income|earnings)\s+before\s+(income\s+)?tax/i, /^pre-?tax\s+(income|earnings)/i],
    // is-tax has to handle a long tail of filer-specific phrasings: the
    // standard "Income tax expense", AMD-style "Provision (benefit) for
    // income taxes" (parenthetical breaks the simpler "provision for tax"
    // pattern), "Income tax provision (benefit)", and benefit-only labels
    // used in loss years. Order matters only as a tiebreaker — the first
    // match wins, but the IS only has one tax row in practice.
    'is-tax': [
      /^(income\s+)?tax\s+expense/i,                          // "Income tax expense", "Tax expense"
      /^provision\s+for\s+(income\s+)?tax/i,                  // "Provision for income taxes"
      /^income\s+taxes?$/i,                                   // "Income taxes" exact
      /^provision\s*\([^)]*\)\s+for\s+(income\s+)?tax/i,      // "Provision (benefit) for income taxes" — AMD
      /^(income\s+)?tax(es)?\s+provision/i,                   // "Income tax provision", "Tax provision (benefit)"
      /^(income\s+)?tax(es)?\s+\([^)]*\)$/i,                  // "Income tax (benefit)" exact
      /^benefit\s+(for|from)\s+(income\s+)?tax/i,             // "Benefit from income taxes" — loss-year label
    ],
    'is-net-income':   [/^net\s+income\s+\(loss\)/i, /^net\s+(income|earnings)$/i, /^net\s+income(\s+attributable)?/i],
  },
  balance_sheet: {
    'bs-cash':          [/^cash\s+and\s+(cash\s+)?equivalents?/i, /^cash$/i],
    'bs-ar':            [/^(trade\s+)?accounts\s+receivable/i, /^receivables/i],
    'bs-inventory':     [/^inventor(y|ies)/i],
    'bs-ppe':           [/^(net\s+)?property,?\s+plant,?\s+and\s+equipment/i, /^(net\s+)?property\s+and\s+equipment/i],
    'bs-total-assets':  [/^total\s+assets/i],
    'bs-ap':            [/^(trade\s+)?accounts\s+payable/i],
    'bs-taxes-payable': [/^(income\s+)?taxes\s+payable/i, /^accrued\s+(income\s+)?taxes/i],
    'bs-debt':          [/^(total\s+)?long-?term\s+debt/i, /^long-?term\s+borrowings?/i],
    'bs-total-liab':    [/^total\s+liabilities$/i],
    'bs-common-stock':  [/^common\s+stock/i, /^additional\s+paid-?in\s+capital/i],
    'bs-retained':      [/^retained\s+earnings/i, /^accumulated\s+deficit/i],
    'bs-total-equity':  [/^total.*(stockholders|shareholders).*equity/i, /^total\s+equity/i],
  },
  cash_flow: {
    'cf-net-income':     [/^net\s+income\s+\(loss\)/i, /^net\s+(income|earnings)/i],
    'cf-depreciation':   [/depreciation/i],
    'cf-deferred-tax':   [/deferred\s+(income\s+)?tax/i],
    'cf-change-ar':      [/accounts\s+receivable/i, /^receivables$/i],
    'cf-change-inv':     [/inventor(y|ies)/i],
    'cf-change-ap':      [/accounts\s+payable/i],
    // CF section totals — broadened to cover non-standard label conventions
    // (Apple writes "Cash generated by operating activities" instead of
    // "Net cash provided by operating activities"; several filers drop
    // the "Net" prefix entirely; "Increase/(Decrease) in cash..." doesn't
    // have a separating space after the verb, so the comma-and-slash
    // patterns confuse strict regexes).
    'cf-operating':      [/cash.*(provided|used|generated|from).*operating\s+activit/i, /^net\s+cash.*operating/i],
    'cf-capex':          [/^(purchases?|payments|additions|investments).*property/i, /capital\s+expenditures?/i],
    'cf-investing':      [/cash.*(provided|used|generated|from).*investing\s+activit/i, /^net\s+cash.*investing/i],
    'cf-debt-issue':     [/(proceeds\s+from).*debt/i, /issuance.*debt/i],
    'cf-equity-issue':   [/(proceeds\s+from|repurchases?\s+of).*(common\s+stock|shares|equity)/i, /issuance.*(common\s+stock|shares)/i, /treasury\s+stock/i],
    'cf-dividends':      [/dividends?\s+paid/i, /payments?\s+(for|of)\s+dividends/i, /^(cash\s+)?dividends/i],
    'cf-financing':      [/cash.*(provided|used|generated|from).*financing\s+activit/i, /^net\s+cash.*financing/i],
    'cf-net-change':     [/(increase|decrease|change).*in\s+cash/i, /^net\s+(increase|decrease|change).*cash/i],
  },
};

export const STATEMENT_KEY_FOR_NODE = {
  IS: 'income_statement',
  BS: 'balance_sheet',
  CF: 'cash_flow',
};

// First regex hit on a non-empty numeric value wins. Returns null if nothing
// matches — callers decide whether to render "—" or fall back to something.
export const matchInStatement = (statementData, patterns, period) => {
  if (!statementData) return null;
  for (const category of Object.keys(statementData)) {
    const items = statementData[category] || [];
    for (const item of items) {
      const label = (item.type || '').trim();
      if (!label) continue;
      for (const pat of patterns) {
        if (pat.test(label)) {
          const v = item.values?.[period];
          if (typeof v === 'number' && !Number.isNaN(v)) {
            return { value: v, sourceLabel: label };
          }
        }
      }
    }
  }
  return null;
};

// Convenience: look up a canonical id (e.g. 'is-revenue') against a full
// statements blob {income_statement, balance_sheet, cash_flow} for a given
// period. Returns the numeric value or null.
export const lookup = (statements, statementKey, lineId, period) => {
  if (!statements || !period) return null;
  const patterns = PATTERNS[statementKey]?.[lineId];
  if (!patterns) return null;
  const found = matchInStatement(statements[statementKey], patterns, period);
  return found?.value ?? null;
};
